# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import blockchain_pb2 as blockchain__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in blockchain_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class BlockchainNodeStub(object):
    """-------------------------
    gRPC Service Definition
    -------------------------

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SubmitTransaction = channel.unary_unary(
                '/blockchain.BlockchainNode/SubmitTransaction',
                request_serializer=blockchain__pb2.SubmitTransactionRequest.SerializeToString,
                response_deserializer=blockchain__pb2.SubmitTransactionResponse.FromString,
                _registered_method=True)
        self.PropagateBlock = channel.unary_unary(
                '/blockchain.BlockchainNode/PropagateBlock',
                request_serializer=blockchain__pb2.PropagateBlockRequest.SerializeToString,
                response_deserializer=blockchain__pb2.PropagateBlockResponse.FromString,
                _registered_method=True)
        self.GetChain = channel.unary_unary(
                '/blockchain.BlockchainNode/GetChain',
                request_serializer=blockchain__pb2.GetChainRequest.SerializeToString,
                response_deserializer=blockchain__pb2.ChainResponse.FromString,
                _registered_method=True)
        self.RegisterPeer = channel.unary_unary(
                '/blockchain.BlockchainNode/RegisterPeer',
                request_serializer=blockchain__pb2.PeerInfo.SerializeToString,
                response_deserializer=blockchain__pb2.Ack.FromString,
                _registered_method=True)
        self.Ping = channel.unary_unary(
                '/blockchain.BlockchainNode/Ping',
                request_serializer=blockchain__pb2.Empty.SerializeToString,
                response_deserializer=blockchain__pb2.Ack.FromString,
                _registered_method=True)


class BlockchainNodeServicer(object):
    """-------------------------
    gRPC Service Definition
    -------------------------

    """

    def SubmitTransaction(self, request, context):
        """Submit a new transaction to a node
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PropagateBlock(self, request, context):
        """Send a newly created block to peers
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetChain(self, request, context):
        """Request the full blockchain for synchronization
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegisterPeer(self, request, context):
        """Optional: register new peers
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Ping(self, request, context):
        """Optional: health check
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BlockchainNodeServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SubmitTransaction': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitTransaction,
                    request_deserializer=blockchain__pb2.SubmitTransactionRequest.FromString,
                    response_serializer=blockchain__pb2.SubmitTransactionResponse.SerializeToString,
            ),
            'PropagateBlock': grpc.unary_unary_rpc_method_handler(
                    servicer.PropagateBlock,
                    request_deserializer=blockchain__pb2.PropagateBlockRequest.FromString,
                    response_serializer=blockchain__pb2.PropagateBlockResponse.SerializeToString,
            ),
            'GetChain': grpc.unary_unary_rpc_method_handler(
                    servicer.GetChain,
                    request_deserializer=blockchain__pb2.GetChainRequest.FromString,
                    response_serializer=blockchain__pb2.ChainResponse.SerializeToString,
            ),
            'RegisterPeer': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterPeer,
                    request_deserializer=blockchain__pb2.PeerInfo.FromString,
                    response_serializer=blockchain__pb2.Ack.SerializeToString,
            ),
            'Ping': grpc.unary_unary_rpc_method_handler(
                    servicer.Ping,
                    request_deserializer=blockchain__pb2.Empty.FromString,
                    response_serializer=blockchain__pb2.Ack.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'blockchain.BlockchainNode', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('blockchain.BlockchainNode', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class BlockchainNode(object):
    """-------------------------
    gRPC Service Definition
    -------------------------

    """

    @staticmethod
    def SubmitTransaction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/blockchain.BlockchainNode/SubmitTransaction',
            blockchain__pb2.SubmitTransactionRequest.SerializeToString,
            blockchain__pb2.SubmitTransactionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PropagateBlock(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/blockchain.BlockchainNode/PropagateBlock',
            blockchain__pb2.PropagateBlockRequest.SerializeToString,
            blockchain__pb2.PropagateBlockResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetChain(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/blockchain.BlockchainNode/GetChain',
            blockchain__pb2.GetChainRequest.SerializeToString,
            blockchain__pb2.ChainResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RegisterPeer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/blockchain.BlockchainNode/RegisterPeer',
            blockchain__pb2.PeerInfo.SerializeToString,
            blockchain__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Ping(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/blockchain.BlockchainNode/Ping',
            blockchain__pb2.Empty.SerializeToString,
            blockchain__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
