# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: blockchain.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'blockchain.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x62lockchain.proto\x12\nblockchain\"\x07\n\x05\x45mpty\"\'\n\x03\x41\x63k\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"j\n\x0bTransaction\x12\x16\n\x0etransaction_id\x18\x01 \x01(\t\x12\x0e\n\x06sender\x18\x02 \x01(\t\x12\x10\n\x08receiver\x18\x03 \x01(\t\x12\x0e\n\x06\x61mount\x18\x04 \x01(\x01\x12\x11\n\ttimestamp\x18\x05 \x01(\x03\"}\n\x05\x42lock\x12\r\n\x05index\x18\x01 \x01(\x05\x12\x11\n\ttimestamp\x18\x02 \x01(\x03\x12-\n\x0ctransactions\x18\x03 \x03(\x0b\x32\x17.blockchain.Transaction\x12\x15\n\rprevious_hash\x18\x04 \x01(\t\x12\x0c\n\x04hash\x18\x05 \x01(\t\"A\n\rChainResponse\x12 \n\x05\x63hain\x18\x01 \x03(\x0b\x32\x11.blockchain.Block\x12\x0e\n\x06length\x18\x02 \x01(\x05\"H\n\x18SubmitTransactionRequest\x12,\n\x0btransaction\x18\x01 \x01(\x0b\x32\x17.blockchain.Transaction\">\n\x19SubmitTransactionResponse\x12\x10\n\x08\x61\x63\x63\x65pted\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"9\n\x15PropagateBlockRequest\x12 \n\x05\x62lock\x18\x01 \x01(\x0b\x32\x11.blockchain.Block\";\n\x16PropagateBlockResponse\x12\x10\n\x08\x61\x63\x63\x65pted\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"\x11\n\x0fGetChainRequest\",\n\x08PeerInfo\x12\x0f\n\x07node_id\x18\x01 \x01(\t\x12\x0f\n\x07\x61\x64\x64ress\x18\x02 \x01(\t2\xf2\x02\n\x0e\x42lockchainNode\x12`\n\x11SubmitTransaction\x12$.blockchain.SubmitTransactionRequest\x1a%.blockchain.SubmitTransactionResponse\x12W\n\x0ePropagateBlock\x12!.blockchain.PropagateBlockRequest\x1a\".blockchain.PropagateBlockResponse\x12\x42\n\x08GetChain\x12\x1b.blockchain.GetChainRequest\x1a\x19.blockchain.ChainResponse\x12\x35\n\x0cRegisterPeer\x12\x14.blockchain.PeerInfo\x1a\x0f.blockchain.Ack\x12*\n\x04Ping\x12\x11.blockchain.Empty\x1a\x0f.blockchain.Ackb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'blockchain_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTY']._serialized_start=32
  _globals['_EMPTY']._serialized_end=39
  _globals['_ACK']._serialized_start=41
  _globals['_ACK']._serialized_end=80
  _globals['_TRANSACTION']._serialized_start=82
  _globals['_TRANSACTION']._serialized_end=188
  _globals['_BLOCK']._serialized_start=190
  _globals['_BLOCK']._serialized_end=315
  _globals['_CHAINRESPONSE']._serialized_start=317
  _globals['_CHAINRESPONSE']._serialized_end=382
  _globals['_SUBMITTRANSACTIONREQUEST']._serialized_start=384
  _globals['_SUBMITTRANSACTIONREQUEST']._serialized_end=456
  _globals['_SUBMITTRANSACTIONRESPONSE']._serialized_start=458
  _globals['_SUBMITTRANSACTIONRESPONSE']._serialized_end=520
  _globals['_PROPAGATEBLOCKREQUEST']._serialized_start=522
  _globals['_PROPAGATEBLOCKREQUEST']._serialized_end=579
  _globals['_PROPAGATEBLOCKRESPONSE']._serialized_start=581
  _globals['_PROPAGATEBLOCKRESPONSE']._serialized_end=640
  _globals['_GETCHAINREQUEST']._serialized_start=642
  _globals['_GETCHAINREQUEST']._serialized_end=659
  _globals['_PEERINFO']._serialized_start=661
  _globals['_PEERINFO']._serialized_end=705
  _globals['_BLOCKCHAINNODE']._serialized_start=708
  _globals['_BLOCKCHAINNODE']._serialized_end=1078
# @@protoc_insertion_point(module_scope)
